# Generated by Django 2.0.4 on 2018-05-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacercita',
            name='dia',
            field=models.DateField(help_text='Formato mes/dia/año'),
        ),
        migrations.AlterField(
            model_name='hacercita',
            name='hora',
            field=models.TimeField(help_text='Formato hora:minutos'),
        ),
    ]
